services:
  app:
    build: .
    image: my-python-app
    networks:
      - app-network
  web:
    image: my-python-app
    command: python -m app.web
    ports:
      - "5000:5000"
    depends_on:
      - runner
    networks:
      - app-network
  runner:
    image: my-python-app
    command: python -m app.runner
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
